import type { IEmployer } from "@/types/IEmployers"

const emp_loyers: IEmployer[] = [
    {
        id: 1,
        name: "Tech Solutions Inc.",
        email: "contact@techsolutions.com",
        phone: "+1-555-0123",
        address: "123 Innovation Drive, Silicon Valley, CA",
        industry: "Technology",
        employees: 150,
        status: "Active",
    },
    {
        id: 2,
        name: "Global Manufacturing Corp",
        email: "hr@globalmfg.com",
        phone: "+1-555-0456",
        address: "456 Industrial Blvd, Detroit, MI",
        industry: "Manufacturing",
        employees: 500,
        status: "Active",
    },
    {
        id: 3,
        name: "Healthcare Partners",
        email: "admin@healthpartners.org",
        phone: "+1-555-0789",
        address: "789 Medical Center Dr, Houston, TX",
        industry: "Healthcare",
        employees: 75,
        status: "Inactive",
    },
    {
        id: 4,
        name: "Tech Solutions Inc.",
        email: "contact@techsolutions.com",
        phone: "+1-555-0123",
        address: "123 Innovation Drive, Silicon Valley, CA",
        industry: "Technology",
        employees: 150,
        status: "Active",
    },
    {
        id: 5,
        name: "Global Manufacturing Corp",
        email: "hr@globalmfg.com",
        phone: "+1-555-0456",
        address: "456 Industrial Blvd, Detroit, MI",
        industry: "Manufacturing",
        employees: 500,
        status: "Active",
    },
    {
        id: 6,
        name: "Healthcare Partners",
        email: "admin@healthpartners.org",
        phone: "+1-555-0789",
        address: "789 Medical Center Dr, Houston, TX",
        industry: "Healthcare",
        employees: 75,
        status: "Inactive",
    },
]

export default emp_loyers
