import { Application } from "@/types/job.types";
const dummyApplications: Application[] = [
  {
    id: 1,
    applicantName: "Jane Doe",
    jobTitle: "House Cleaner",
    status: "Pending",
    stage: "Application Review",
    message: "I'm available full time and have 2 years experience.",
    email: "jane@example.com",
    phone: "+1-555-0123",
    appliedDate: "2024-12-01",
    experience: "2 years",
    availability: "Full-time",
  },
  {
    id: 2,
    applicantName: "John Smith",
    jobTitle: "Delivery Driver",
    status: "Interview Scheduled",
    stage: "Phone Interview",
    message: "Certified driver with clean record.",
    email: "john@example.com",
    phone: "+1-555-0124",
    appliedDate: "2024-12-02",
    experience: "5 years",
    availability: "Full-time",
  },
  {
    id: 3,
    applicantName: "Alice Johnson",
    jobTitle: "House Cleaner",
    status: "Rejected",
    stage: "Application Review",
    message: "Experienced with cleaning and customer service.",
    email: "alice@example.com",
    phone: "+1-555-0125",
    appliedDate: "2024-11-28",
    experience: "3 years",
    availability: "Part-time",
    rejectionReason: "Overqualified for the position",
  },
  {
    id: 4,
    applicantName: "Bob Lee",
    jobTitle: "Delivery Driver",
    status: "Accepted",
    stage: "Offer Extended",
    message: "Fast and reliable driver.",
    email: "bob@example.com",
    phone: "+1-555-0126",
    appliedDate: "2024-11-25",
    experience: "4 years",
    availability: "Full-time",
  },
  {
    id: 5,
    applicantName: "Sarah Wilson",
    jobTitle: "House Cleaner",
    status: "Final Interview",
    stage: "In-Person Interview",
    message: "I'm available full time and have 2 years experience.",
    email: "sarah@example.com",
    phone: "+1-555-0127",
    appliedDate: "2024-11-30",
    experience: "2 years",
    availability: "Full-time",
  },
];

export { dummyApplications };
